### PR TITLE
Fix goal pruners

### LINKED ISSUE #140: [Hotfix] Fix goal pruners
Gol pruners currently work with a missmatched set of category names and ids. It can never compare them so a pruner will always filter out all goals.

### PR DESCRIPTION
**Pull request by Floha258**
Closes #140

### CODE REVIEW

File: api/src/core/generation/BoardGenerator.ts [hunk 1]
```diff
@@ -83,8 +83,8 @@ export class BoardGenerator {
             }
             goal.categories.forEach((cat) => {
                 const prev =
-                    this.goalsByCategory[this.categoriesByName[cat].id] ?? [];
-                this.goalsByCategory[this.categoriesByName[cat].id] = [
+                    this.goalsByCategoryId[this.categoriesByName[cat.name].id] ?? [];
```
Comment (cjs8487) [inline api/src/core/generation/BoardGenerator.ts]: If we have the category object and the the id goalsByCatId map, can't we omit the lookup by name here (and on the next line)?

File: api/src/core/generation/BoardGenerator.ts [hunk 2]
```diff
@@ -115,8 +115,8 @@ export class BoardGenerator {
...
```
Comment (cjs8487) [inline api/src/core/generation/BoardGenerator.ts]: Same as earlier, we shouldn't need to lookup by name to obtain the id anymore since we have the category object

File: api/src/core/generation/GlobalAdjustments.ts [hunk 3]
```diff
@@ -35,10 +35,10 @@ const synergize: GlobalAdjustment = (generator, lastPlaced) => {
 
 const boardTypeMax: GlobalAdjustment = (generator, lastPlaced) => {
     lastPlaced.categories.forEach((cat) => {
-        generator.categoryMaxes[cat]--;
-        if (generator.categoryMaxes[cat] === 0) {
-            generator.goalsByCategory[
-                generator.categoriesByName[cat].id
+        generator.categoryMaxes[cat.name]--;
```
Comment (cjs8487) [inline api/src/core/generation/GlobalAdjustments.ts]: Should we do category maxes by id as well?

File: api/src/core/generation/SRLv5.ts [hunk 4]
```diff
@@ -104,7 +104,7 @@ export const generateSRLv5 = (
     function checkLine(i: number, typesA: string[]) {
```
Comment (cjs8487) [inline api/src/core/generation/SRLv5.ts]: Should convert this to using the Category object

**Review by cjs8487 — CHANGES_REQUESTED** [review]

**Review by cjs8487 — APPROVED** [review]
